# Site settings
author: Martin A.
title: Martin A.'s journeys through learning
header-img: img/home-bg.png
email: mdacht777@gmail.com
copyright_name: Martin A.
description: > # this means to ignore newlines until "baseurl:"
  Martin A.'s journeys through learning
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mdacht777

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
